---
title: "Fe-BR: Base de Dados Brasileira de Ferro do Solo"
---

Contribuir
=================================

Você pode contribuir com quaisquer dados de conteúdo de ferro do solo, seja qual for o método analítico usado,
a forma e profundidade de amostragem, ou a localização geográfica das amostras analisadas, desde que esses
dados sejam fruto de suas atividades e/ou estejam sob sua responsabilidade. Mas antes de preparar seu conjunto
de dados para contribuição, recomendamos que você leia atentamente as diretrizes abaixo e, caso restarem 
dúvidas, entre em [contato](contact.html) conosco. Assim poderemos discutir detalhes importantes e garantir 
que o seu (e o nosso) tempo seja gasto de maneira racional.

## Forma de Submissão

A forma de submissão dos dados depende do formato e do número de registros (número de amostras) que você tem 
em mãos:

* Caso os dados estejam no formato analógico (relatórios, dissertações e teses), pedimos que você faça a sua
  digitalização usando o nosso modelo de planilha eletrônica que contém nomes padronizados para as variáveis
  (veja abaixo).
* Se os dados já estiverem no formato digital e o número de registros for pequeno (< 1000 registros), pedimos
  que os mesmos sejam organizados usando também o nosso modelo de planilha eletrônica (veja abaixo).
* Mas se você tiver um volume muito grande de dados (> 1000 registros) já no formato digital, envie-nos uma 
  mensagem para estudarmos a forma mais apropriada para o sua submissão.

Nosso modelo de planilha eletrônica para organização dos dados foi construído usando o mesmo padrão
internacional usado pelo World Soil Information Service ([WoSIS](http://www.isric.org/data/wosis)) -- o que
explica o uso de termos em inglês (veja abaixo). Versões para usuários de LibreOffice (formato ODS) e 
Microsoft Office (formato XLS) podem ser descarregadas de:

* LibreOffice: https://github.com/samuel-rosa/Fe-BR/raw/master/templates/template.ods
* Microsoft Office: https://github.com/samuel-rosa/Fe-BR/raw/master/templates/template.xls

A planilha eletrônica possui cinco abas (com nomes em inglês):

* `README`: Aqui você encontra informações gerais sobre o preenchimento das demais abas.
* `dataset`: Nesta aba você inclui as informações necessárias à identificação do conjunto de dados. São 18 os
  campos a ser preenchidos, mas você tem liberdade para acrescentar quaisquer informações que julgar
  pertinente. Essas informações são necessárias para garantir a apropriada citação do conjunto de dados no 
  futuro.
* `metadata`: Aqui você encontra a definição e descrição dos campos a serem preenchidos nas abas `profile` e
  `horizon`.
* `profile`: Aqui você fornece informações sobre os perfis ou pontos de observação e amostragem do solo, tais
  como as coordenadas geográficas, a data de amostragem e a classificação do solo. Note que o termo `profile`
  é usado aqui fazendo referência à qualquer tipo de observação e amostragem do solo, seja um perfil 
  propriamente dito ou uma tradagem ou amostragem da camada superficial. Além disso, não há necessidade de 
  fornecer todas as informações solicitadas: por exemplo, em muitos casos, a classificação taxonômica não está
  disponível.
* `horizon`: Nessa aba você insere os dados dos horizontes e/ou camadas amostradas onde o conteúdo de ferro
  tenha sido determinado. Qualquer método analítico é aceito, sendo sua responsabilidade a apropriada 
  identificação e descrição dos mesmos tanto aqui como na aba `metadata`. Por exemplo, o nome 
  `fe_sulfurico_eaa` refere-se ao conteúdo de ferro (`fe`) determinado por espectrometria de absorção atômica
  (`eaa`) no extrato de solução de ácido sulfúrico (`sulfurico`).

Você verá em cada uma das abas da planilha eletrônica o símbolo `(...)`. Esse símbolo indica a posição da aba
em que você pode adicionar informações adicionais relacionadas ao conteúdo da respectiva aba. Entre em 
[contato](contact.html) caso você tenha dúvidas sobre como inserir informações adicionais.

## Métodos Analíticos

Você viu acima que a identificação dos dados de conteúdo de ferro na aba `horizon` é feita usando símbolos que
se referem ao tipo de extrator ou complexante usado e ao método de determinação. Esse tipo de identificação é
importante por dois motivos:

1. Para que você possa informar dados do conteúdo de ferro de uma mesma amostra de solo obtidos usando 
diferentes métodos analíticos.
2. Para que nós possamos organizar apropriadamente os dados na base de dados com vistas a sua posterior
harmonização.

Por exemplo, é comum determinar o conteúdo de ferro do solo extraído com oxalato ácido de amônio e
citrato-ditionito-bicarbonato a fim de quantificar o grau de cristalinidade dos óxidos de ferro no solo, usando
como método de determinação a espectrometria de absorção atômica. Nesse caso, a identificação é feita usando
os símbolos `fe_oxalato_eaa` e `fe_ditionito_eaa`, respectivamente.

Abaixo são apresentados os símbolos indicados para os principais extratores/complexantes e métodos de 
determinação.

<br>

| Símbolo       | Extrator/Complexante                                 |
|---------------|------------------------------------------------------|
| `sulfurico`   | ácido sulfúrico                                      |
| `oxalato`     | oxalato ácido de amônio                              |
| `ditionito`   | citrato-ditionito-bicarbonato                        |
| `pirofosfato` | pirofosfato de sódio                                 |
| `triacido`    | ácido perclórico + ácido nítrico + ácido fluorídrico |
| `dtpa`        | DTPA                                                 |
| `mehlich`     | Mehlich                                              |
Table: Símbolos indicados para os principais extratores e complexantes.

<br>

| Símbolo  | Método de determinação                                              |
|----------|---------------------------------------------------------------------|
| `eaa`    | espectrometria de absorção atômica                                  |
| `edta`   | complexometria com EDTA                                             |
| `eam`    | espectrometria de absorção molecular                                |
| `icpms`  | espectrometria de massa com plasma acoplado indutivamente           |
| `icpoes` | espectrometria de emissão atômica com plasma acoplado indutivamente |
Table: Símbolos indicados para os principais método de determinação.

<br>

Note que as listas de símbolos não são exaustivas. Entre em [contato](contact.html) conosco caso você use
métodos analíticos diferentes daqueles apresentados aqui para que possamos definir os símbolos mais
apropriados.

<!-- ## Origem dos Dados -->

<!-- [perfis](#perfis) -->

<!-- [amostras individuais](#amostras) -->

<!-- ## Dados de Perfis do Solo {#perfis} -->

<!-- ## Dados de Amostras Individuais {#amostras} -->


