---
title: "Fe-BR: Base de Dados Brasileira de Ferro do Solo"
---

Dados
=================================

Veja a classificação dos cientistas do solo que já contribuíram com dados de conteúdo de ferro do solo.

```{r, echo=FALSE}
ctb <- 
  function (name, inst, number) {
    data.frame(Nome = name, Instituição = inst, Contribuição = number)
  }
rank <- 
  function (people) {
    people <- people[order(people$Contribuição, decreasing = TRUE), ]
    people <- cbind(Posição = 1:nrow(people), people)
    rownames(people) <- NULL
    return (people)
  }
```

## Dados Pedológicos

```{r, echo=FALSE}
ctb <- 
  function (name, inst, number) {
    data.frame(Nome = name, Instituição = inst, Contribuição = number)
  }
people <- 
  rbind(
    ctb("Elias Mendes Costa", "Universidade Federal Rural do Rio de Janeiro", 17)
  )
knitr::kable(rank(people), format = "html", table.attr = "width='100%'")
```

<br>

## Dados Edafológicos

```{r, echo=FALSE}
people <- 
  rbind(
    ctb("José Maria Filippini Alba", "Embrapa Clima Temperado", 196)
  )
knitr::kable(rank(people), format = "html", table.attr = "width='100%'")
```
