---
title: "Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo"
---

## APRESENTAÇÃO

Junte-se a nós num ***esforço colaborativo inédito*** da comunidade de cientistas do solo brasileira. O 
***objetivo***: construir um repositório de dados de ferro do solo centralizado, público e gratuito, com 
cobertura nacional.

Nós acreditamos que o uso sustentável do solo para aplicações ambientais no Brasil exige o conhecimento 
preciso e acurado da distribuição horizontal e vertical do conteúdo de ferro no solo. Por quê? Porque, em 
alguns locais, ***os óxidos de ferro podem perfazer até 80% da massa do solo***!

Os óxidos de ferro são bem conhecidos por sua forte interação com a matéria orgânica do solo, influenciando 
assim a quantidade de carbono que o solo consegue armazenar de forma estável. Os óxidos de ferro também são 
bem conhecidos pela sua forte afinidade com íons fosfato, determinando assim a disponibilidade de fósforo para
as plantas. A intrincada relação entre fósforo e matéria orgânica reforça a necessidade do conhecimento da
variação tridimensional do teor de ferro do solo em todo o território brasileiro. Tal conhecimento poderia 
ajudar, por exemplo, na melhoria dos sistemas de classificação do solo, no desenvolvimento de sistemas 
avançados de recomendação que assegurem o uso mais eficiente de fertilizantes fosfatados, e na construção de
políticas públicas de uso e ocupação do solo que respeitem as reais capacidades desse precioso e não-renovável
bem natural.

## Como participar?

***Participar é muito fácil!*** Você só precisa [contribuir](contribute.html) com quaisquer dados de conteúdo
de ferro do solo que sejam fruto de suas atividades, seja qual for o método analítico usado, a forma e
profundidade de amostragem, ou a localização geográfica das amostras analisadas.
Veja os [conjuntos de dados já disponíveis](data.html)!

Você também pode participar ajudando no processamento dos dados, corrigindo inconsistências, revisando nosso
trabalho, encontrando coordenadas espaciais, enviando sugestões e, é claro, divulgando nosso projeto entre 
seus colegas. Você pode, inclusive, fazer da sua participação em nosso projeto o seu próprio projeto de 
pesquisa (mestrado, doutorado, pós-doutorado). Entre em [contato](contact.html) conosco!

## O que você ganha com isso?

Acredite, você tem muito a ganhar!

Primeiro, além da enorme satisfação de colaborar com a comunidade científica e valorizar os dados produzidos 
em suas atividades, aumentando as chances de ser citado, você terá a oportunidade de usar um repositório de 
dados padronizados e georreferenciados, com milhares de registros cobrindo o território nacional, para 
exercitar sua criatividade científica. Por exemplo, você poderá:

* Levantar dos métodos analíticos usados no Brasil e propor padronizações,
* Avaliar e propor mudanças em critérios de sistemas taxonômicos,
* Produzir mapas para o seu estado ou todo o território brasileiro,
* Identificar áreas prioritárias para novos estudos e amostragens,
* E muitos mais.

Lembre-se que ao colaborar conosco você também estará colaborando com a Política de Dados Abertos
([PDA](http://wiki.dados.gov.br/Politica-de-Dados-Abertos.ashx)).

***Mas não é só isso!*** Caso sua contribuição esteja entre as quatro maiores, ou você nos ajudar
significativamente no processamento dos dados, você será agraciado com a coautoria de um artigo a ser 
submetido para publicação na revista [Earth System Science Data](http://earth-system-science-data.net/) 
(Fator de Impacto > 8).

***Quer mais?***  Fique muuuuito famoso com seu nome citado na página do projeto!

Estamos contando com sua contribuição!
